name 'chef-provisioning-vagrant-helper'
maintainer 'Irving Popovetsky'
maintainer_email 'irving@chef.io'
license 'all_rights'
description 'Installs/Configures chef-provisioning-vagrant-helper'
long_description 'Installs/Configures chef-provisioning-vagrant-helper'
version '0.2.0'
source_url       'https://github.com/irvingpop/chef-provisioning-vagrant-helper'
issues_url       'https://github.com/irvingpop/chef-provisioning-vagrant-helper/issues'
