name 'chef-provisioning-vagrant-helper'
maintainer 'Irving Popovetsky'
maintainer_email 'irving@chef.io'
license 'all_rights'
description 'Installs/Configures chef-provisioning-vagrant-helper'
long_description 'Installs/Configures chef-provisioning-vagrant-helper'
version '0.1.0'
